// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6E2cFVvBpEIYQg_0T0MpYTuMal5WPc-s',
    appId: '1:812116549631:web:9cb8cb9d6a42ff787311ca',
    messagingSenderId: '812116549631',
    projectId: 'quranapp-4fc3f',
    authDomain: 'quranapp-4fc3f.firebaseapp.com',
    storageBucket: 'quranapp-4fc3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxNjI1jV6Dc0QjOjtt6XBcbSUxDyWxuY',
    appId: '1:812116549631:android:34cda2acbbd03c0e7311ca',
    messagingSenderId: '812116549631',
    projectId: 'quranapp-4fc3f',
    storageBucket: 'quranapp-4fc3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLaR1MrmqDE2qrYODGlbmzA_JDnyRrwA',
    appId: '1:812116549631:ios:2499cd0b04973efc7311ca',
    messagingSenderId: '812116549631',
    projectId: 'quranapp-4fc3f',
    storageBucket: 'quranapp-4fc3f.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLaR1MrmqDE2qrYODGlbmzA_JDnyRrwA',
    appId: '1:812116549631:ios:2499cd0b04973efc7311ca',
    messagingSenderId: '812116549631',
    projectId: 'quranapp-4fc3f',
    storageBucket: 'quranapp-4fc3f.firebasestorage.app',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6E2cFVvBpEIYQg_0T0MpYTuMal5WPc-s',
    appId: '1:812116549631:web:ecb41da6732928b97311ca',
    messagingSenderId: '812116549631',
    projectId: 'quranapp-4fc3f',
    authDomain: 'quranapp-4fc3f.firebaseapp.com',
    storageBucket: 'quranapp-4fc3f.firebasestorage.app',
  );

}